### ISSUE TITLE
sef issue when redirected

### ISSUE THREAD

**Issue by raramuridesign** [C-Lodder/Profile-Edit-Redirect#2]
Hi, thanks for the plugin works well except the plugin ignores sef and uses 
component in the url string

is this possible to fix ?

**Comment by C-Lodder** [comment]
@raramuridesign - I've made a small tweak, could you test please?  >> https://github.com/C-Lodder/Profile-Edit-Redirect/commit/d6e9de671c5363390ffb90548c1e19ebe86d2460

**Comment by raramuridesign** [comment]
@C-Lodder That seems to have worked. Nice one...
